# Figma Webhook
version: "3.7"

services:
  app:
    image: figma-hook:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    expose:
      - 80
    command:
      ["--hostname", "0.0.0.0", "--port", "8080", "--migrate"]
